project:
  type: website
  output-dir: docs

website:
  title: "Esercitazioni di esame - Corso di Misure Industriali"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - text: Librerie
        icon: boxes
        menu:
          - text: Digital Signal Processing
            icon: cpu
            href: dig_signal_proc.R
            
          - text: Formattazione grafica
            icon: bar-chart
            href: graphics.R
        
      - href: ex1.html
        text: Esercitazione 1

format:
  html:
    css: styles.css
    toc: true
    lang: it
    theme:
      light: flatly
    font:
        base: "Source Sans 3"
        monospace: "JetBrains Mono"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300
    fig-align: center

