project:
  type: website
  output-dir: docs

website:
  title: "Esercitazioni di esame - Corso di Misure Industriali"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ex1.html
        text: Esercitazione 1

format:
  html:
    css: styles.css
    toc: true
    lang: it
    theme:
      light: flatly
    font:
        base: "Source Sans 3"
        monospace: "JetBrains Mono"

