project:
  type: website
  output-dir: docs

website:
  title: "Esercitazioni di esame - Corso di Misure Industriali"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - text: Librerie
        icon: boxes
        menu:
          - text: Digital Signal Processing
            icon: cpu
            href: dsp_library.html
            
          - text: Formattazione grafica
            icon: bar-chart
            href: graph_library.html
        
      - text: Esercitazioni
        icon: journal-text
        menu:
          - href: ex1.html
            text: Esercitazione 1
          - href: ex2.html
            text: Esercitazione 2
          - href: ex3.html
            text: Esercitazione 3
          - href: ex4.html
            text: Esercitazione 4
          - href: ex5.html
            text: Esercitazione 5

format:
  html:
    include-in-header: include/password.html
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    lang: it
    theme:
      light: flatly
    font:
        base: "Source Sans 3"
        monospace: "JetBrains Mono"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300
    fig-align: center
    meta:
      - name: robots
        content: noindex

